import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'inspaverse',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col items-center justify-center p-24">
          <div className="z-10 max-w-5xl w-full items-center justify-between text-sm lg:flex pb-64">
            {children}
          </div>
        </main>
      </body>
    </html>
  )
}
