import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Nav } from './Nav'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'inspaverse',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={
          (inter.className, 'min-h-screen p-4 w-full flex flex-col gap-48')
        }
      >
        <Nav />
        <main className="flex flex-col items-center justify-center">
          <div className="items-center justify-between text-sm lg:flex">
            {children}
          </div>
        </main>
      </body>
    </html>
  )
}
